name: emoticon-swift
options:
  bundleIdPrefix: com.george
targets:
  emoticon-swift-macos:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/emoticon-swift
        excludes:
          - Info-macOS.plist
          - Info-iOS.plist
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.george.emoticon-swift
        SWIFT_VERSION: 6.0
        INFOPLIST_FILE: Sources/emoticon-swift/Info-macOS.plist
  emoticon-swift-ios:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/emoticon-swift
        excludes:
          - Info-iOS.plist
          - Info-macOS.plist
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.george.emoticon-swift-ios
        SWIFT_VERSION: 6.0
        PRODUCT_NAME: emoticon-swift-ios
        INFOPLIST_FILE: Sources/emoticon-swift/Info-iOS.plist
